### ISSUE TITLE
用此方案打包提交 AppStore 无法通过检查

### ISSUE THREAD

**Issue by EyreFree** [Natoto/fixFlutterEngine#1]
携带 1.0 的 Flutter.framework 后打包提交出现如下回复，移除该 framework 后恢复正常：

![](https://upload-images.jianshu.io/upload_images/1018190-98a512443181fb15.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

```
Invalid Bundle - Ensure that app executables and bundled frameworks use consistent architectures
```

**Comment by Natoto** [comment]
> 携带 1.0 的 Flutter.framework 后打包提交出现如下回复，移除该 framework 后恢复正常：
> 
> ![](https://camo.githubusercontent.com/02eb2c00510dfc21bcb34737565a869852cf822f/68747470733a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313031383139302d393861353132343433313831666231352e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)
> 
> ```
> Invalid Bundle - Ensure that app executables and bundled frameworks use consistent architectures
> ```

此flutter.framework 只支持arm64的，工程配置应该只支持arm64
