### ISSUE TITLE
请问一下Flutter新版本的内存泄漏如何解决？貌似这里只提供到了1.0版本

### ISSUE THREAD

**Issue by NickHu150** [Natoto/fixFlutterEngine#2]
请问一下Flutter新版本的内存泄漏如何解决？貌似这里只提供到了1.0版本，我们更新到了1.5

**Comment by Natoto** [comment]
> 请问一下Flutter新版本的内存泄漏如何解决？貌似这里只提供到了1.0版本，我们更新到了1.5

开发中

**Comment by NickHu150** [comment]
@Natoto  官方到了1.5版本居然还不修复内存泄漏的问题，也是醉了，请问您这边大约什么时候能发布1.5的FIX~，我们准备上个Flutter，结果IOS因为这个问题卡住了~

**Comment by Natoto** [comment]
> @Natoto 官方到了1.5版本居然还不修复内存泄漏的问题，也是醉了，请问您这边大约什么时候能发布1.5的FIX~，我们准备上个Flutter，结果IOS因为这个问题卡住了~

本周可以提供，可以加q群 了解进度  群聊【flutter移动开发】：217429001

**Comment by Huyamin150** [comment]
@ @Natoto 给个QQ号吧，这个链接点进去QQ没反应
